import type { SerializedProfile } from "@/lib/profile"

export type ArtifactFixture = { id: string; locale: "id" | "en"; audience: string; objective: string; themeFamily?: "professional-minimal" | "editorial-portfolio" | "formal-institutional" | "modern-technical"; profile: SerializedProfile }

function profile(name: string, headline: string, summary: string, experiences: Array<[string, string, string, string[]]>, skills: string[], locale: "id" | "en"): SerializedProfile {
  return {
    id: "fixture-profile", fullName: name, headline, summary, email: `${name.toLowerCase().replace(/[^a-z]+/g, ".")}@example.test`, phone: "+62 812 0000 0000", location: "Jakarta", photoUrl: null,
    links: { linkedin: "https://linkedin.com/in/example", portfolio: "https://portfolio.example.test" }, uiLocale: locale, docLocale: locale, targetRegion: "domestic", opportunityTypes: [], preferredTone: "warm", urgency: null, targetExamScore: null, onboardingComplete: true, onboardingStep: 4, profileCompletion: 90,
    experiences: experiences.map(([title, organization, contextNotes, achievements], index) => ({ id: `exp-${index}`, userProfileId: "fixture-profile", type: "project", title, organization, startDate: `202${index + 2}-01`, endDate: index === 0 ? null : `202${index + 3}-01`, current: index === 0, location: "Jakarta", description: contextNotes, achievements: achievements as never, contextNotes, order: index, createdAt: new Date(0), updatedAt: new Date(0) })),
    educations: [{ id: "edu-fixture", userProfileId: "fixture-profile", institution: "Universitas Indonesia", degree: "Sarjana", field: locale === "id" ? "Bidang Studi" : "Field of Study", startDate: "2021-08", endDate: null, current: true, gpa: "3.78", description: null, order: 0 }],
    skills: skills.map((name, index) => ({ id: `skill-${index}`, userProfileId: "fixture-profile", name, category: index < 3 ? (locale === "id" ? "Keahlian inti" : "Core") : (locale === "id" ? "Pendukung" : "Supporting"), proficiency: null, context: null, order: index })), certifications: [], languages: [],
  } as unknown as SerializedProfile
}

export const artifactFixtures = {
  "indonesian-law-student": { id: "indonesian-law-student", locale: "id", audience: "Perekrut dan mitra organisasi", objective: "Menunjukkan kesiapan riset hukum dan kontribusi publik", themeFamily: "formal-institutional", profile: profile("Nadya Putri Rahma", "Mahasiswa hukum yang berfokus pada akses keadilan", "Menghubungkan riset regulasi, pendampingan klinik hukum, dan edukasi publik menjadi rekomendasi yang dapat digunakan komunitas.", [["Asisten Peneliti", "Pusat Studi Hukum", "Menganalisis kebijakan akses keadilan dan putusan pengadilan.", ["Menganalisis 48 putusan untuk memetakan pola pertimbangan hakim.", "Menyusun dua ringkasan regulasi untuk diskusi pemangku kepentingan."]], ["Koordinator Program", "Klinik Hukum Kampus", "Mengelola lokakarya literasi hukum bersama komunitas.", ["Mengoordinasikan 12 relawan untuk empat lokakarya.", "Menyederhanakan materi hak pekerja bagi 180 peserta."]]], ["Riset Hukum", "Analisis Kebijakan", "Legal Writing", "Fasilitasi", "Public Speaking"], "id") },
  "software-engineer": { id: "software-engineer", locale: "en", audience: "Engineering hiring teams", objective: "Show evidence-backed product engineering impact", themeFamily: "modern-technical", profile: profile("Arif Pratama", "Software engineer building reliable product systems", "Product engineer focused on dependable web platforms, observability, and clear collaboration across design and operations.", [["Senior Software Engineer", "Nusantara Systems", "Led reliability improvements for a transaction platform.", ["Reduced incident recovery time by 36% through runbooks and service telemetry.", "Delivered a migration used by 14 internal teams."]], ["Product Engineer", "Cahaya Labs", "Built workflow tools for operations teams.", ["Automated a review workflow handling 8,000 monthly records."]]], ["TypeScript", "System Design", "Observability", "PostgreSQL", "React", "Mentoring"], "en") },
  "fresh-graduate-cv": { id: "fresh-graduate-cv", locale: "id", audience: "Perekrut", objective: "CV ATS lulusan baru", profile: profile("Dina Maharani", "Lulusan baru analisis data", "Lulusan statistika dengan proyek analisis dan pengalaman organisasi.", [["Data Intern", "Contoh Data", "Membersihkan dan menganalisis data operasional.", ["Memvalidasi 12.000 baris data untuk laporan bulanan."]]], ["Excel", "SQL", "Python"], "id") },
  "experienced-professional-cv": { id: "experienced-professional-cv", locale: "en", audience: "Executive recruiters", objective: "Two-page evidence-led CV", profile: profile("Maya Santoso", "Operations leader", "Operations leader with cross-functional delivery experience.", [["Operations Lead", "Example Group", "Led regional operations.", ["Improved SLA attainment from 82% to 94%."]]], ["Operations", "Planning", "Leadership"], "en") },
  "scholarship-cover-letter": { id: "scholarship-cover-letter", locale: "id", audience: "Komite beasiswa", objective: "Surat motivasi berbasis bukti", profile: profile("Raka Wijaya", "Penggerak pendidikan komunitas", "Berpengalaman mengelola kelas komunitas.", [["Relawan Pengajar", "Rumah Belajar", "Mengajar matematika mingguan.", ["Mendampingi 30 siswa selama satu semester."]]], ["Mengajar", "Fasilitasi", "Perencanaan"], "id") },
  "odp-application-essay": { id: "odp-application-essay", locale: "id", audience: "Tim seleksi ODP", objective: "Esai aplikasi yang menjawab prompt", profile: profile("Sari Utami", "Lulusan ekonomi", "Tertarik pada layanan keuangan inklusif.", [["Project Lead", "Finance Society", "Memimpin riset literasi keuangan.", ["Mewawancarai 60 responden di tiga kecamatan."]]], ["Riset", "Ekonomi", "Komunikasi"], "id") },
  "technical-project": { id: "technical-project", locale: "en", audience: "Product and engineering leaders", objective: "Explain a technical project as a case study", themeFamily: "modern-technical", profile: profile("Kevin Halim", "Platform engineer", "Builds secure developer platforms and deployment workflows.", [["Platform Migration Lead", "Atlas Platform", "Reworked deployment architecture for safer releases.", ["Moved 22 services to standardized pipelines.", "Reduced failed deployments by 41%."]]], ["Kubernetes", "CI/CD", "Security", "Go", "Terraform"], "en") },
  "academic-presentation": { id: "academic-presentation", locale: "id", audience: "Dosen dan mahasiswa", objective: "Menyampaikan temuan akademik secara runtut", themeFamily: "formal-institutional", profile: profile("Alya Ramadhani", "Peneliti kebijakan publik", "Mengkaji implementasi layanan publik digital melalui pendekatan campuran.", [["Peneliti", "Laboratorium Kebijakan", "Meneliti adopsi layanan publik digital.", ["Mengolah 320 respons survei dan 18 wawancara mendalam."]]], ["Metode Campuran", "Analisis Kebijakan", "R", "Wawancara"], "id") },
} satisfies Record<string, ArtifactFixture>
